### ISSUE TITLE
In multi-user environments, /tmp/run_loop_host_cache causes permissions issues

### ISSUE THREAD

**Issue by onfoot** [calabash/run_loop#121]
If two users use run_loop on the same Mac, both instances try to create or use the same file in /tmp directory, causing permission denied errors. I'm not sure if it is safe to change the permissions, but wouldn't it be better to make the file's name unique, at least prepended with user's login name?

If there's a way to define a different path for run_loop_host_cache then great, my problem will be partially solved and I'm sorry if I didn't notice such option.

**Comment by jmoody** [comment]
@onfoot 

That can be fixed easily.  Pull requests welcome.

**Comment by jmoody** [comment]
And thanks for the request.

**Comment by jmoody** [comment]
Fixed.  Will be part of the next run-loop release.

**Comment by onfoot** [comment]
Much appreciated!
