### ISSUE TITLE
After successfully touching a UIAlertView button, there is ~10 second delay before the alert is dismissed

### ISSUE THREAD

**Issue by ShuheiOno** [calabash/run_loop#125]
Hello.
I'm testing show the AlertView(with Yes and No button) and touch the No button.
When AlertView appears, touch the 'No' button.
It works correctly, but It took about 10sec.
1. AlertView appears.
2. Execute 'touch' to tap the cancel button.  
   ~ waiting about 10 sec ~
3. AlertView disappers.

Place where time is at stake:
RunLoop::Core.read_response
`index_if_found = output.index(START_DELIMITER)`

In this method, turning loop until finding 'index_if_found', it take about 10 sec.
(In iOS7, it takes about 14sec.)
I think it's too long.
Is this just a matter of my environment?
How long will it take in your environment?

I measured the time by inserting puts statement like following:
ex: RunLoop::Core.read_response (insert to l573 and l604)

```
if index_if_found
  puts "=============== index_if_found in!:#{Time.now}"
  offset = offset + index_if_found
```

```
else 
  puts "=============== index not found: #{Time.now}"
  sleep(0.1)
end
```

ex:my step definition file

```
puts "touch start:#{Time.now}"
touch("label marked:'#{button}'") 
puts "touch end  :#{Time.now}"
```

Results (iPnone6 iOS8.0):

```
2015-02-04 10:33:51 +0900: Trying write of command 5:uia.tapOffset('{:x 120, :y 370.75}') at index 5
=============== index not found: 2015-02-04 10:33:51 +0900
=============== index_if_found in!:2015-02-04 10:33:51 +0900
=============== index not found: 2015-02-04 10:33:51 +0900
 ... (omission)
=============== index not found: 2015-02-04 10:34:00 +0900
=============== index_if_found in!:2015-02-04 10:34:01 +0900
=============== index_if_found in!:2015-02-04 10:34:01 +0900
2015-02-04 10:34:01 +0900: validate index written for index 5 ok
=============== index not found: 2015-02-04 10:34:01 +0900
=============== index not found: 2015-02-04 10:34:01 +0900
=============== index_if_found in!:2015-02-04 10:34:01 +0900
Result
{"status"=>"success", "value"=>true, "index"=>5}
    When I touch the "No" button on alertView               # features/step_definitions/common_steps.rb:202
      touch start:2015-02-04 10:33:51 +0900
      touch end  :2015-02-04 10:34:01 +0900
    Then I should see 3 thumbnails                          # features/step_definitions/common_steps.rb:118
```

My environment:
- XCode 6.1 on Yosemite
- calabash-cucumber 0.12.2
- run_loop 1.2.6
- test target
  - iPhone6 (real device) iOS8.0
  - iPhone5 (real device) iOS7.1

Thanks.

**Comment by jmoody** [comment]
@ShuheiOno 

I have seen this in the wild.  I don't have good sense of what is to blame.  Thanks for the bug report.

**Comment by jmoody** [comment]
I *believe* this is because there is a filter step happening the calabash JavaScript in the on_alert() method.  I think this filtering is causing the delay.

**Comment by jmoody** [comment]
Next step:  Figure out where the bottle neck is.

**Comment by bhumikasrinivas** [comment]
Hi Joshua, was this fixed? I still keep seeing this error in our tests once in a while.

**Comment by jmoody** [comment]
No.

**Comment by jmoody** [comment]
This is fixed because we no longer use UIAutomation.
