### ISSUE TITLE
Environment variables not being passed to the application

### ISSUE THREAD

**Issue by renatorodrigues** [calabash/run_loop#178]
Until 1.2.6, I was capable of passing environment variables – e.g, "-e VARIABLE_NAME value" – to the application. But with the following versions, it seems that feature became broken.

I've always sent those variables through the launcher:

    options = {
        :args => [
            "-e AUTOMATION_CAN_USE_FEATURE_A NO",
            "-e AUTOMATION_CAN_USE_FEATURE_B NO"
        ]
    }

In order to read one of these variables, one can do the following:

    NSDictionary *environment = [[NSProcessInfo processInfo] environment];
    NSString *argument = environment[@"AUTOMATION_CAN_USE_FEATURE_A"];
    BOOL canUseFeatureA = argument ? [argument boolValue] : fallbackFeatureA;

It is also possible to set these variables through the "Manage Schemes..." option on Xcode, under the "Environment Variables" section:

![screenshot 2015-05-05 18 05 02](https://cloud.githubusercontent.com/assets/246079/7478302/b0680ce6-f351-11e4-8af1-0cf2dac372d8.png)

Other way to pass arguments to the application, is through name/value pairs (which is the same as using the "Arguments Passed On Launch" section on the previous image):

    options = {
        :args => ['-NSDoubleLocalizedStrings', 'YES']
    }

I have done some tests and I've concluded that passing arguments through name/value pairs works fine but through the "-e" option does not work after the version 1.2.6 of run_loop.

More on the subject of launch arguments: http://nshipster.com/launch-arguments-and-environment-variables/

**Comment by jmoody** [comment]
@renatorodrigues 

Excellent reporting. :+1: 

I _think_ that if you do this:

```
:args => [
        '-e', 'AUTOMATION_CAN_USE_FEATURE_A', 'NO',
        '-e' 'AUTOMATION_CAN_USE_FEATURE_B', 'NO'
    ]
```

you will be able to pass these arguments.

Can you give it a try?

The reason for this change in 1.2.6 was to allow a more stable interaction with Apple's instruments.

There was a blurb in the Apple's 6.3 release notes about passing arguments to the the iOS Simulator applications.  Now I can't find the release notes - they are not the ones posted by Apple, but those it distributes with beta releases.  I will keep looking.

In the meantime, here is a interesting message from Xcode 6.3.1:

```
$ xcrun xcodebuild -version
Xcode 6.3.1
Build version 6D1002

$ xcrun simctl help launch
Usage: simctl launch [-w | --wait-for-debugger] <device> <app identifier> [<argv 1> <argv 2> ... <argv n>]

If you want to set environment variables in the resulting environment, set them in the calling environment with a SIMCTL_CHILD_ prefix.
```

This suggests to me that in Xcode 6.3* environments, all environment variables need to be prefixed with SIMCTL_CHILD_.

**Comment by jmoody** [comment]
To clarify, we don't use `simctl` to launch the simulator, we use `instruments`.

The instruments man page has not changed for Xcode 6.3*

**Comment by renatorodrigues** [comment]
@jmoody, your solution proved to be right. In the past, in attempts to solve this problem, I've attempted some variations but not that one you have provided.

Thank you very much. :+1:

**Comment by jmoody** [comment]
@renatorodrigues 

Let's keep an eye on this.  I think something nasty is going to be coming from Apple re:  environment variables and application arguments.

Already I have had one client who has not been able to set the app's language with with launch arguments.

**Comment by daniele-xp** [comment]
Hi!
With XCode 8 and iOS10 emulators I can no longer pass environment variables through launcher.relaunch options with:

```
options = { :args => [
        '-e', 'FORCE_JIFFY_FEATURE_FLAG', 'disabled',
        '-e', 'ATTEMPTS_AFTER_WHICH_POS_WILL_BE_CONNECTED', '10'
]}
Calabash::Launcher.launcher.relaunch(options)
```

Emulator seems to ignore env variables now.

Anyone found a solutions?
We use env variables to drive some app behaviors during several tests
