### ISSUE TITLE
Calabash script halt for some time and then throws error while execution.

### ISSUE THREAD

**Issue by vebhrocks** [calabash/run_loop#206]
I'm trying to execute cucumber command using my real device and it is throwing an error. That is,

 "Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
  Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError. 
   Logfile /var/folders/8q/6pyry8k10cn09p5phfjy22q80000gq/T/run_loop20150828-1996-pgfyu/run_loop.out"

I am not getting what exactly I need to set? B'coz in the Xcode I have selected my real device and through that I can communicate but while initiating through cucumber it stuck. 

What I am doing exactly and my environment?

1. I'm on accessing MAC(Which is having xcode) mini over and iPhone over wifi. the device is connected to MAC. 

2. I have installed calabash on MAC with below environment.
      2.1 Calabash-ios version 0.14.3
      2.2 Ruby 2.2.2(rbenv)
      2.3 xcodebuild version 6.4
      2.4 MAC-OS version 10.10.4
      2.5 iPhone 6, iOS 8.3 
Let me know if anything I have missed here.
I have set the environment for DEVICE_TARGET, BUNDLE_ID, and DEVICE_ENDPOINT parameter.

First time when there is no app on device I'm giving below command:

 NO_LAUNCH=1 DEVICE_TARGET=http://deviceip:37265 cucumber

 And for next time my command is:

NO_LAUNCH=0 DEVICE_TARGET=http:/deviceip:37265 cucumber

Can anybody help me for this issue, that would be highly appreciated.

**Comment by jmoody** [comment]
The `NO_LAUNCH` environment variable should not be used.

* http://calabashapi.xamarin.com/ios/file.ENVIRONMENT_VARIABLES.html#label-NO_LAUNCH

Your command should look like this:

```
$ DEVICE_ENDPOINT=http://deviceip:37265 DEVICE_TARGET=5dd<snip>912
```

The DEVICE_TARGET should be the UDID of the device you are trying to test on.

You can find the UDID of devices connected by USB:

```
$ xcrun instruments -s devices
```

**Comment by vebhrocks** [comment]
Ohh okay!! 

I have made necessary changes and it run well.

Lot of thanks @jmoody.
