### ISSUE TITLE
iOS 9 has different text for privacy alerts

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#237]
- [x] Need to run the Permission.app. https://github.com/Oddj0b/Permissions
- [x] Update run-loop JavaScript
- [x] Update UITest JavaScript

**Comment by chawang** [comment]
Screenshot of the 9.0 system dialog:

![screen shot 2015-09-14 at 10 27 07 am](https://cloud.githubusercontent.com/assets/4691250/9856720/2d9fa332-5acb-11e5-8e2b-c37f6549c394.png)

**Comment by jmoody** [comment]
I have run the Permission.app on an iOS 9 beta device.

Attached is a zip with the alerts.

[iOS9-alerts.zip | uploaded via ZenHub](https://files.zenhub.io/55f7e91af0dc49cd55fc33bc)

=== 

![calendar](https://cloud.githubusercontent.com/assets/466104/9873369/9beb26de-5b9f-11e5-92be-d3d3d13f16cc.png)

===

![camera](https://cloud.githubusercontent.com/assets/466104/9873370/9becb12a-5b9f-11e5-94ee-d1be37eddc00.png)

===

![location](https://cloud.githubusercontent.com/assets/466104/9873371/9bf52bfc-5b9f-11e5-80e4-25f20f655b1b.png)

===

![microphone](https://cloud.githubusercontent.com/assets/466104/9873372/9bf609c8-5b9f-11e5-8c69-95af527c2490.png)

===

![motion fitness](https://cloud.githubusercontent.com/assets/466104/9873373/9bfcdb86-5b9f-11e5-8ceb-6845f17226e4.png)

===

![permissions](https://cloud.githubusercontent.com/assets/466104/9873374/9c02291a-5b9f-11e5-9d1e-72f83f10acd7.png)

===

![photos](https://cloud.githubusercontent.com/assets/466104/9873375/9c1232ba-5b9f-11e5-9b80-34f29ad5d616.png)

===

![reminders](https://cloud.githubusercontent.com/assets/466104/9873376/9c1ae220-5b9f-11e5-9a51-12155e4c3f12.png)

===

![twitter](https://cloud.githubusercontent.com/assets/466104/9873377/9c1fd01e-5b9f-11e5-8059-e3f4ffd96f06.png)

**Comment by sapieneptus** [comment]
@jmoody I don't understand why the alert in @chawang 's screenshot wasn't dismissed. `run_loop` should have caught that alert:

https://github.com/calabash/run_loop/blob/develop/scripts/run_loop_fast_uia.js#L206
https://github.com/calabash/run_loop/blob/develop/scripts/run_loop_basic.js#L197
https://github.com/calabash/run_loop/blob/develop/scripts/run_loop_host.js#L223
https://github.com/calabash/run_loop/blob/develop/scripts/run_loop_shared_element.js#L206

**Comment by sapieneptus** [comment]
@jmoody It seems most of these should already be supported.

[x] update run_loop js: #251

**Comment by sapieneptus** [comment]
- [x] update UITest run_loop js: https://github.com/xamarin/Xamarin.UITest/pull/645

**Comment by sapieneptus** [comment]
@jmoody Just tried running the Permissions app in XTC, I see calabash 2.0 is still not supported there. Are there Calabash 0.x cucumbers we could use to verify that this is working, or should I port the features over to Calabash 0.x?

**Comment by jmoody** [comment]
@sapieneptus No.  And it is sad.  I made a mistake implementing it in Calabash 2.0. 

>  I don't understand why the alert in @chawang 's screenshot wasn't dismissed. run_loop should have caught that alert:

I think the regex:

```
"access to your location while you use the app"
```

is not matched.

Looks like the Permissions app needs also a "use your location in the background" row.

**Comment by sapieneptus** [comment]
@jmoody I think the regex that run_loop is checking is `/access your location/`. 

The dialog is:

"Allow <AppName> to _access your location_ [...]"

Shouldn't that match?

**Comment by sapieneptus** [comment]
![img_0001](https://cloud.githubusercontent.com/assets/3009852/9888257/e6abb716-5ba8-11e5-8e3a-bc0ca46dbf94.png)

I guess we should just make it case insensitive?

**Comment by jmoody** [comment]
@sapieneptus There you go.  I think you are correct; run-loop should have dismissed that alert.  The next step would be to see if UITest has the same regex - I believe it does.

ATTN: @chawang

**Comment by jmoody** [comment]
Fixed.

**Comment by chawang** [comment]
Interestingly, the dialogs ARE being dismissed on the 9.0's BUT not on the 8.4.1's.
[Link to run.](https://testcloud.xamarin.com/test/abc6d6f2-584d-42d6-9aec-e5e319d3e29e/?step=0_0_0)
![screen shot 2015-09-16 at 11 32 44 am](https://cloud.githubusercontent.com/assets/4691250/9914415/ac287e9e-5c66-11e5-85e9-5a1967638e8a.png)

**Comment by jmoody** [comment]
Is the alert popping too soon?

**Comment by Sweekriti91** [comment]
I ran a test on the app using a physical device, iPhone 5 running 8.1.1 with the dev UITest nuget package, and it auto dismissed 2 dialogs, first for Location (seen above) and second one for Push Notifications and only after that launched the Repl. The Alert popped up immediately after the app started and then was automatically dismissed.

**Comment by jmoody** [comment]
@Sweekriti91 I think you are saying that it is working as expected.  Is that correct?

**Comment by Sweekriti91** [comment]
@jmoody Yup, but this is on a 8.1.1 device. On the cloud, its the 8.4.1 device which isn't auto dismissing the alert.

**Comment by jmoody** [comment]
@Sweekriti91 Gotcha.  It seems like a timing issue.  The app is popping the alert too quickly - before instruments can take control of the app.

Since this is appearing in UITest, can we track it on the UITest issue page?

https://github.com/calabash/calabash-ios/wiki/Managing-Privacy-Alerts%3A--Location-Services%2C-APNS%2C-Contacts

**Comment by Sweekriti91** [comment]
@jmoody I think you're right, seems like a timing issue. Sure, I'll move this to the UITest issue page.
