### ISSUE TITLE
App life cycle: delete data/Library/Caches/com.apple.LaunchServices-134.csstore

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#249]
### Motivation

Might block CoreSimulator launches after uninstall app.

**Comment by sapieneptus** [comment]
@jmoody  https://github.com/calabash/run_loop/pull/252

I tried to follow the convo from slack, I believe this is the correct place to delete the file. Please lmk if otherwise. 

Rake unit tests still pass, but it sounded like the sims were working fine for you anyway (?)

**Comment by jmoody** [comment]
You are correct.  I was not seeing the same behavior as @john7doe or @rasmuskl.

**Comment by jmoody** [comment]
Fixed.
