### ISSUE TITLE
reset simulator does not wipe the keychain

### ISSUE THREAD

**Issue by xinsight** [calabash/run_loop#265]
I'm using the iOS keychain (Security/SecBase.h) to store login credentials. The flag `RESET_BETWEEN_SCENARIOS=1` doesn't completely reset the simulator as the credentials are not wiped. (However, they are wiped if you use the Simulator menu option "Reset all Content and Settings...".)

A workaround for Xcode 6 was to wipe the keychain on the current device in `launch.rb`:

```
  if ENV['DEVICE_TARGET']
    device = ENV['DEVICE_TARGET']
    print "*** DELETING KEYCHAIN ***\n"
    cmd="rm ~/Library/Developer/CoreSimulator/Devices/#{device}/data/Library/Keychains/keychain-2-debug.db*"
    `#{cmd}`
  end
```

But this doesn't seem to work in Xcode 7. (The keychain files exist on disk, but deleting the files from a running simulator doesn't prevent them from being used.)

Are there any ways to configure run_loop to fully wipe the device before each scenario?

**Comment by jmoody** [comment]
Calabash iOS has a Keychain API.

```
keychain_clear
```

Call it after the app has been launched.

https://github.com/calabash/ios-smoke-test-app/blob/master/CalSmokeApp/features/keychain.feature

Alternatively, you can use simctl to reset the simulator:

```
$ xcrun simctl erase <UDID>
```

There are caveats re: simctl erase.  The simulator.app needs to be closed and the device must be the Shutdown state.

This sounds like a feature.

Let me know if `keychain_clear` works.

**Comment by xinsight** [comment]
Fantastic, `keychain_clear` works great.

I had tried using `xcrun simctl erase` but it seemed to wedge the Simulator so I wasn't able to launch simulators.

Thanks for your help!
