### ISSUE TITLE
Running out of disk space because of cached instruments files

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#276]
### Motivation

@nfrydenholm, @TeresaP, and I have all run out of disk space on our Jenkins machines because of files that instruments is caching.

We should identify and remove these files.

**Comment by mholtman** [comment]
@jmoody We're running into this same issue on our Jenkins nodes. Is there a short-term fix / work around that you know of to have Instruments cache less aggressively? 

Incidentally, it drops the run_loop caches in /private/var/folders/...

**Comment by jmoody** [comment]
@mholtman No, there is no way to tell instruments to not to make these Cache files.

> Incidentally, it drops the run_loop caches in /private/var/folders/...

On my Jenkins machine, the files are located here:

```
/Library/Caches/com.apple.dt.instruments/
```

Are you saying that you are seeing large disk usage of /private/var/ ?

Calabash does stage files to /private/var, but I haven't seen these be a problem.

The largest files I see in /private/var are from Xcode itself and not from anything instruments related.  If you find something, can you paste the file path here?

**Comment by mholtman** [comment]
@jmoody 

The path where we're seeing heavy usage is here:

/private/var/folders/qb/tz674hms6p90wqrs53_yq_lh0000gp/T

Your mileage may vary, but in that folder are subfolders all starting with 'run_loop...' . Within each of those run_loop folders is a another 'trace.trace' folder which takes up the majority of space. 

Have we inadvertently made Calabash chatty? Is there a way I can verify logging settings?

**Comment by jmoody** [comment]
> Your mileage may vary, but in that folder are subfolders all starting with 'run_loop...'

Are you using a custom Instruments trace template by any chance?  One that is trying to profile your app's memory while running cucumber?

This is normal.  run-loop creates a new directory for every run.  It is strange that your files are large.  I am seeing directory sizes (combined) of tens of MB on my Jenkins machine.

> Have we inadvertently made Calabash chatty? Is there a way I can verify logging settings?

No.

If this is a big problem you can tell run-loop to put the files somewhere else, like `./calabash-results` and then clean that directory after a run.


```ruby
options = {
  :results_dir => './calabash-results'
}

# In your hooks.
...relaunch(options)
```

**Comment by nfrydenholm** [comment]
It sounds like the same issue as we see. We have not (at least not on purpose) set up any trace or anything. As I recall it happened after a "big bang" update, where we updated Xcode, SDK and Calabash all at once. Version-details are explained in this post https://groups.google.com/forum/#!searchin/calabash-ios/cache/calabash-ios/e5GTKJUbdKg/N4DTGcQOhJgJ

Our current solution (read: hack) is to run a job on jenkins, that will run on all our jenkins nodes every couple of hours, and delete the folders.

**Comment by jmoody** [comment]
@mholtman @nfrydenholm 

I need some advice.  I don't see the large .trace files locally so I have no idea how large they are or what your memory constraints are.

I am thinking about tracking where run-loop creates the tmp results directories and deleting them following this rule:

* Before launch, search for these tmp directories and delete all but the youngest 5.

Is 5 a good magic number?  If possible want to avoid adding yet-another command line variable to control the behavior of run-loop.

I am going to do the same for the /Library/Caches/com.apple.dt.instruments/ directories, but I might hit permissions problems.

**Comment by mholtman** [comment]
@jmoody 5 sounds like good number. Leaving that many at the beginning of each build shouldn't case any issues. 

In my setup, we see run_loop directories in the ~25MB range.

**Comment by nfrydenholm** [comment]
I see same size - each run_loop dir is about 25MB.

I would say delete all :smile: - but that's only because I don't know what I should use them for in the first place, so keeping 5 should only be to make sure you don't break the simulator. But since you plan to hook in and delete before launch, the simulator is not running at all, so it shouldn't influence it. 
Our current hack is a separate jenkins job, that has no idea if tests are running or not - it just deletes everything in the folder.

**Comment by jmoody** [comment]
@mholtman @nfrydenholm

> delete all vs. keep 5

There can be some interesting debugging information in these files; especially when trying to debug a new UIA strategy.

My plan (in progress) is to store these files in `~/.run-loop/results`

**Comment by jmoody** [comment]
#299 fixes the /var/folders explosion.

**Comment by jmoody** [comment]
#304 fixes the /Library/Caches/com.apple.dt.instruments explosion

**Comment by jmoody** [comment]
@mholtman @nfrydenholm @TeresaP

I have cut a 1.5.6.pre1 release.

If you get a chance, can you try this locally and on your Jenkins machines?

Thanks!

jjm

**Comment by mholtman** [comment]
@jmoody 

We have it set to run all night, so we'll let you know what it looks like tomorrow.

**Comment by mholtman** [comment]
@jmoody

Ran this overnight. Seemed to work as intended. Thanks for the quick fix.

**Comment by TeresaP** [comment]
@jmoody We're running into an issue like: Xcrun timed out after 2.29 seconds executing 'xcrun instruments -s templates' at the moment. Maybe the new run-loop will fix that problem as well. I will see if I can try it.

**Comment by jmoody** [comment]
@TeresaP What version of run-loop?

The timeout on all xcrun commands (including that one) is 30 seconds.

**Comment by TeresaP** [comment]
@jmoody 1.5.5 and we are running on device. Now trying a reinstall of Xcode.
