### ISSUE TITLE
Unable to touch buttons on OS level permission alerts

### ISSUE THREAD

**Issue by akozlik** [calabash/run_loop#324]
When prompting for Bluetooth and Location Services permissions we are unable to touch the accept button.

Our scenario is that a user sees an introductory slideshow that notifies them we need location services and bluetooth. The user presses a continue button and then the permission request is executed. Each permission request is on a separate slide in the slideshow.

I've used the Calabash console to inspect the entire view hierarchy available when the alert has been displayed and the permission dialogues do not appear at all. There is no reference to a UIAlertView, UIAlertControllerView or buttons with the acceptance text.

We tried implementing the suggestion within [Managing Privacy Alerts](https://github.com/calabash/calabash-ios/wiki/Managing-Privacy-Alerts%3A--Location-Services%2C-APNS%2C-Contacts) to add a delay to the alert but found the same result.

We've also run through the iOS Smoke Test app and attempted to recreate the steps outlined in [alerts_steps.rb](https://github.com/calabash/ios-smoke-test-app/blob/master/CalSmokeApp/features/step_definitions/alerts_steps.rb). This also resulted in failed tests.

Thanks for any assistance!

**Comment by joelmartinez** [comment]
what device and version of iOS are you running the smoke tests with?

**Comment by akozlik** [comment]
iPhone 6 Simulator running iOS 8.4

**Comment by jmoody** [comment]
What version of run-loop are you using?

I am going to make some references to our side conversation and repeat some information that I've already conveyed - it will be helpful for others.

> When prompting for Bluetooth and Location Services permissions we are unable to touch the accept button.

Calabash should automatically dismiss that Location Services alert.  I am not yet sure why it is not.

The Bluetooth alert is one that we haven't see yet; I can add that presently.

Here are some suggestions:

```
> query("all view:'_UIAlertControllerView'")
> uia("uia.alert()")
> uia_query_windows(:alert)


if !query("view marked:'Allow'").empty?
  uia_tap_mark("Allow")
end
```

**Comment by jmoody** [comment]
@akozlik I have been away this week, but I am ready today to pick up this issue again.

**Comment by jmoody** [comment]
@akozlik Any updates?  Can I close this issue?

**Comment by jmoody** [comment]
@joelmartinez Let me know if I need to reopen this issue.  Thanks!

**Comment by akozlik** [comment]
Hey guys,

Unfortunately I got pulled off of Calabash integration for a while but once I'm back on I'll come back to this issue if we continue to have it. Thank you for your help.
