### ISSUE TITLE
RunLoop.send_command performance degrades significantly over time

### ISSUE THREAD

**Issue by lguipeng** [calabash/run_loop#330]

**Comment by jmoody** [comment]
What method are you talking about?

**Comment by lguipeng** [comment]
RunLoop.send_command

**Comment by lguipeng** [comment]
My  Environment ：
ruby 2.0.0
OS X 10.10.5
run_loop 1.5.6

**Comment by TeresaP** [comment]
I just ran a test overnight that executes a command every 0.5 seconds and there was a pretty obvious performance degradation by the end of the night.  Due to performance issues, each step was initially carried out every 4 seconds (even though we only wait 0.5 second between steps) but by the end they were executed every 3 minutes. https://gist.github.com/TeresaP/e38b42a7bddeac5db8cb

**Comment by jmoody** [comment]
Thanks @lguipeng and @TeresaP.

Good job reproducing. 

I will take a look, but I hope that 0.17 will allow :preferences on iOS 9 devices.

**Comment by jmoody** [comment]
ATTN @krukow

**Comment by lguipeng** [comment]
I think it may be in the RunLoop.read_response () need to match a lot of strings cause more and more slow,based on this, I set options[:no_flush]  true, and after running RunLoop.send_commond() 2000 times, it takes 1.3s everytime, if I do not set options[:no_flush] true, it takes 3s everytime

**Comment by krukow** [comment]
@jmoody it would be nice to confirm that it is `read_response` that is the problem. We do track an offset into the file which should be fast:

https://github.com/calabash/run_loop/blob/d9ade86f2662759703c2c983de24585626ef2fd1/lib/run_loop/core.rb#L629

I wouldn't delay the next release to fix this: (1) it's an edge case to have a single test running for that long, (2) With iOS 9 support for :preferences this is less relevant, and (3)  XCUITest (or similar) support in the future

**Comment by jmoody** [comment]
`:preferences` and `:shared_element` are not options in iOS 9. :(

**Comment by jmoody** [comment]
@lguipeng I cannot reproduce.

Can you share a project that reproduces?
