### ISSUE TITLE
Dutch APNS dialog is not automatically dismissed

### ISSUE THREAD

**Issue by GlennWilson** [calabash/run_loop#337]
- [x] ~~Reproduce alert in Permissions.app~~ Cannot reproduce, but created an issue [#9](https://github.com/calabash/Permissions/issues/9)
- [x] Include Dutch localization

```
wil u berichten stuern.  
Berichten kunnen bestaan uit meldingen geluiden en symboolbadges. 
Dit kunt u opegeven in Instellingen

Dismiss with: OK
```

**Comment by jmoody** [comment]
I think this is not from the Messages.app - it is Notifications.
