### ISSUE TITLE
Isolating the ScriptAgent no access to UniqueDeviceID bug

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#34]
### Summary

I am testing Briar on iOS 8 GM with Xcode 6 GM.   Run-loop is using the :host strategy.

The first Scenario passes.  The next Scenario fails to launch the app.

I _think_ this error, which appears when the first step finishes, is important.

```
SpringBoard[47] <Warning>: Entitlement com.apple.multitasking.termination required to kill applications.
```

The second Scenario fails. The third Scenario passes.

However, at this point the device is stuck in an infinite loop spitting out the following error messages. 

```
MobileGestaltHelper[909] <Error>: libMobileGestalt MobileGestalt.c:273: server_access_check denied access to question UniqueDeviceID for pid 796 
ScriptAgent[796] <Error>: libMobileGestalt MobileGestaltSupport.m:170: pid 796 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled
ScriptAgent[703] <Error>: libMobileGestalt MobileGestalt.c:534: no access to UniqueDeviceID (see <rdar://problem/11744455>)
```

**Comment by Caiflower** [comment]
Xcode 8.3.2/iOS 10.3 libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID ，

**Comment by jmoody** [comment]
@Caiflower Is this causing a test to fail?  If so, please open a new issue.
