### ISSUE TITLE
App installation fails on iOS 9.0

### ISSUE THREAD

**Issue by JennyGr** [calabash/run_loop#343]
I'm using XCode Version 7.1.1 (7B1005) with calabash-ios 0.16.4, calabash.frameworkb 0.16.4 and run_loop 1.5.6.

Running the calabash tests on a simulator for iOS 9.0 fails with the following issue:

```
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
  Calabash::Cucumber::Launcher::StartError: 
  
  "Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.
  
  Logfile: /Users/jenkins/.run-loop/results/2015-11-19_15-25-23/run_loop.out
  
  Instruments Usage Error : Specified target process is invalid: <BUNDLE_ID>
  instruments, version 7.1.1 (59040)
  usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]
  
  
   (Calabash::Cucumber::Launcher::StartError)
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:778:in `new_run_loop'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:635:in `relaunch' 
  /Users/jenkins/....../features/support/01_launch.rb:27:in `Before' 
```

**Comment by TeresaP** [comment]
What's APP_BUNDLE_PATH set to and what are your other environment variables? What simulator device did you build from xcode? What have you tried so far?

**Comment by JennyGr** [comment]
I tried with all the simulators. For all the other versions is OK. Just iOS 9.0 throws this error.
The APP_BUNDLE_PATH is the same as the one I use for the rest of the iOS versions, where it works just fine.
The XCode can build and install on the iOS 9.0. Calabash doesn't though.

**Comment by jmoody** [comment]
What is the APP_BUNDLE_PATH?

**Comment by JennyGr** [comment]
/Users/jenny/Documents/.../.../.../***-***-testapp/Build/Calabash-iphonesimulator/<name_of_the_app>.app

**Comment by jmoody** [comment]
Thanks @JennyGr I will be taking a look shortly.

**Comment by jmoody** [comment]
@JennyGr I have not been able to reproduce.  Are you using Xcode 7.2 now?  Is this still happening?

**Comment by jmoody** [comment]
Also, have you updated to Calabash 0.17.0?

**Comment by JennyGr** [comment]
I will try both updates (still using XCode 7.1.1 and Calabash 0.16.4) and see if I can reproduce the issue.
Thanks.

**Comment by jmoody** [comment]
Apologies that this is taking so long to resolve.

**Comment by jmoody** [comment]
@JennyGr I cannot reproduce.

I invite you join us to discuss this problem in Gitter:

* https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by JennyGr** [comment]
I finally managed to find time and update XCode and Calabash. After the update the issue doesn't occur anymore. It seems the previous XCode-Calabash versions I had installed where incompatible.

**Comment by jmoody** [comment]
@JennyGr Thanks for the follow up.
