### ISSUE TITLE
No french localization for handling system dialogs like permissions

### ISSUE THREAD

**Issue by therealjohn** [calabash/run_loop#369]
There is a need for localized translations to handle permission dialogs. 

For example, a customer has an app that is in French, and the permission dialogs that appear are in French.

**Comment by jmoody** [comment]
Thanks!  This is in the queue.

**Comment by jmoody** [comment]
This will be part of the next run-loop release later this week.

It will be part of UITest 1.3.x - release date TBD (but soon).
