### ISSUE TITLE
Force UTF-8 encoding when checking for simulator pid

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#373]
```
  Scenario: 一个用户在未登录状态下购买金小宝然后解约                                 # features/jxb_unlogin.feature:3
 invalid byte sequence in UTF-8 (ArgumentError)
 /Users/wj/.rvm/gems/ruby-2.2.2/gems/run_loop-2.0.3/lib/run_loop/core_simulator.rb:518:in `split'
 /Users/wj/.rvm/gems/ruby-2.2.2/gems/run_loop-2.0.3/lib/run_loop/core_simulator.rb:518:in `running_simulator_pid'
 /Users/wj/.rvm/gems/ruby-2.2.2/gems/run_loop-2.0.3/lib/run_loop/core_simulator.rb:291:in `launch_simulator'
```

Related to **Pass all `read` calls through utf-8 filter** #230

**Comment by jmoody** [comment]
I reviewed the code and I believe that I am already forcing UTF-8 encoding.  

Something else it causing the problem.

I need to ask for some help solving this problem.  Is there any chance we could do a tmate session on the machine that has this problem?

https://tmate.io/

This would involve me ssh'ing into your machine and working with you via text chat to find out what the problem is.

I recommend Gitter as the chat client:

https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link

If this is not possible or convenient, then please run the following in the calabash-ios console:

$ bundle exec calabash-ios console

> xcrun = RunLoop::Xcrun.new
> args = ["xcrun", "ps", "x", "-o", "pid,command"]
> hash = xcrun.exec(args)
> File.open("ps.log", "w:UTF-8") { |file| file.write(hash[:out]) }
> exit

Then mail me the ps.log to the email address in my GitHub profile:

https://github.com/jmoody

Thanks!

**Comment by wangjiang0318** [comment]
sent ps.log via email ,thank you!

**Comment by wangjiang0318** [comment]
Sorry the machine could not be connected from internet due to the firewall rules in my company

**Comment by jmoody** [comment]
@wangjiang0318 

Awesome!  I reproduced the problem using ps.log and the fix in progress.

Thanks!

**Comment by TobiasRoikjer** [comment]
@jmoody Do we have a test that reproduces this problem? Or a simple Ruby script

**Comment by jmoody** [comment]
There is an rspec test.

**Comment by jmoody** [comment]
@wangjiang0318

The fix will be released today.  It will only work for ruby >= 2.1.

**Comment by wangjiang0318** [comment]
OK,Thank you! I will have a test with reinstall the latest version.

**Comment by wangjiang0318** [comment]
@jmoody it works. Thank you！
