### ISSUE TITLE
Privacy:  problems dismissing health kit slide over

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#374]
**[iOS] User unable to run tests on some iPhone devices due to HealthKit permission popup** [#748](https://github.com/xamarin/test-cloud-operations/issues/748)

**Comment by jmoody** [comment]
Here are some facts:

* HealthKit is not supported iOS < 8 or on iPads
* The UIAutomation `onAlert()` method is not triggered so we cannot automatically dismiss this page.

We can, however, interact with it via `uia_*` calls.

I made a PR: https://github.com/calabash/Permissions/pull/19

This is the secret sauce:

```
    sleep(2.0)
    uia_tap_mark("All Categories On")
    sleep(2.0
    uia_tap_mark("Allow")
```

I need to nail down the specific timings.  `wait_for_none_animating` does not work because the view is _outside_ the app view heirarchy.

The only thing we can do here is to add a Calabash iOS API for dismissing this view for a set of languages. 

@krukow 

I am inclined to point users to this example and to _not_ implement anything new.

**Comment by jmoody** [comment]
ATTN: @King-of-Spades

**Comment by King-of-Spades** [comment]
Thanks, I added an additional note to my planned article to cover this info: https://trello.com/c/PqjPHSzc

**Comment by jmoody** [comment]
@King-of-Spades The example is complete.

You'll need to translate this to UITest, but the approach is the same.  Let me know if you need help.

1. Trigger the Health Access modal view by performing a UI action
2. Use UIAutomation calls enable specific permissions
3. Use UIAutomation calls to dismiss the Health Access modal view
4. Wait for the Health Access modal view to disappear.

### Notes

Health Kit is not available on iPads or before iOS 7.  I added an Objective-C category to the _top level_ view of the controller to test for Health Kit availability.  This could also have been done as a `backdoor`.

```Objective-C
#import <HealthKit/HealthKit.h>
@interface UIView (CalabashPermissions)

- (BOOL) isHealthKitAvailable;

@end

@implementation UIView (CalabashPermissions)

// HealthKit is avaiable on iOS > 7 and only on some devices
- (BOOL) isHealthKitAvailable {
  return NSClassFromString(@"HKHealthStore") && [HKHealthStore isHealthDataAvailable];
}

@end
```

In my tests:

```ruby
  if query("view marked:'page'", :isHealthKitAvailable).first == 1
    @supports_health_kit = true
  else
    @supports_health_kit = false
  end
```

In my tests, I branch on availability - the same Steps run, but different actions are performed based on availability.

The tests are further complicated by UI differences between iOS 8 and 9.  And they are even more complicated by the fact that different form factors have different text.  In our example, the text "Sex" is alternatively "Sex" or "Biological Sex" based on form factor.  This is text generated by Apple; the user has no control over this text.

Because we dipping down into UIAutomation, we have to use explicit sleeps because we have no Wait API for UIAutomation.

```ruby
  if @supports_health_kit
    if RunLoop::Environment.ci?
      pause = 10.0
    elsif RunLoop::Environment.xtc?
      pause = 8.0
    else
      pause = 3.0
    end

    if ios8?
      # Skip the 'Sex' row because the text varies across simulator,
      # physical devices, and form factors - the 6 plus has: Biological Sex
      ["Body Mass Index", "Height", "Weight",
       "Date of Birth", "Steps"].each do |mark|

        uia_call(:tableView, {:scrollToElementWithName => mark})
        sleep(pause)
        uia_call([:switch, {:marked => mark}], {:setValue => true})
        sleep(pause)
      end

      uia_tap_mark("Done")
    else
      sleep(pause)
      uia_tap_mark("All Categories On")
      sleep(pause)
      uia_tap_mark("Allow")
    end
  else
    # nop - device or iOS does not support health kit
    puts "   Device or iOS version does not support HealthKit"
  end
```

The entire example can be found in the [Permissions app](https://github.com/calabash/Permissions). 

```
Scenario: Enabling Health Kit permissions
  Given I can see the list of services requiring authorization
  When I touch the Health Kit row
  Then I see the HealthKit modal view or Not Supported alert
  Then I can enable HealthKit permissions and dismiss the page
```

**Comment by jmoody** [comment]
@TobiasRoikjer If you have a minute, can you comment on the approach?  See any problems?

**Comment by King-of-Spades** [comment]
@jmoody beyond my simplistic usage of InvokeUia (below) to tap a labeled element, I don't really know. I may either need some extensive help with this or someone else to contribute it. (It doesn't help that I haven't really used Calabash much yet either.) 

I may be able to coordinate with @GlennWilson since we work in the same office and he's good at explaining similar stuff; (and has also written some internal troubleshooting articles for Test Cloud); though that's assuming he understands your description above.

```cs
[Test]
public void AppLaunches ()
{
	app.Screenshot ("First screen.");
	app.InvokeUia ("uia.query('[:view {:marked \"OK\"}]')"); 
	app.InvokeUia ("uia.tapMark(\"OK\")"); 
}
```

**Comment by King-of-Spades** [comment]
I've made a note of this issue here: https://trello.com/c/PqjPHSzc
