### ISSUE TITLE
Using fbsimctl instead of instruments

### ISSUE THREAD

**Issue by tapthaker** [calabash/run_loop#375]
FBSimulatorControl is promising and it now also has a cli for the same ( Still under development) if all goes well we should be able to launch multiple simulators ( upto 10 ) and run tests in parallel. I am willing to contribute to this but just wanted some pointers on how should I be proceeding.

**Comment by jmoody** [comment]
Does fbsimctl interface with UIAutomation?  At first glance, it does not.  The reason we launch apps with instruments is connect with the UIAutomation API.

**Comment by jmoody** [comment]
I am closing this.

**Comment by tapthaker** [comment]
FBSimulatorControl directly doesn't but there is another framework by Facebook that can do this aka [WebDriverAgent](https://github.com/facebook/webdriveragent).

**Comment by jmoody** [comment]
We have no plans to change run-loop to use anything other than instruments.  Since UIAutomation is deprecated, we have to change our focus to supporting XCUITest.  We have being evaluating the Facebook's tools.  It is not clear yet whether we can or should adopt them.
