### ISSUE TITLE
unable run automation scripts on simulator

### ISSUE THREAD

**Issue by prathimak** [calabash/run_loop#376]
When i run the tests on simulator i got below error

undefined method `strip' for nil:NilClass (NoMethodError)
 /Users/prathima/.rvm/gems/ruby-2.2.1/gems/rspec-expectations-2.14.5/lib/rspec/matchers/method_missing.rb:9:in `method_missing'
 /Users/prathima/.rvm/gems/ruby-2.2.1@global/gems/run_loop-1.5.6/lib/run_loop/version.rb:60:in `initialize'

calabash-"calabash-cucumber", "0.15.0"
xcode: 7.2

i have't made any recent changes suddenly stops working

**Comment by jmoody** [comment]
Please update to 0.17.1. 

Calabash 0.15.0 does not support Xcode 7.2.
