### ISSUE TITLE
Broken pipe @ io_write_nonblock while running tests on simulator

### ISSUE THREAD

**Issue by TeresaP** [calabash/run_loop#395]
While running tests on simulator, I occasionally encounter: Broken pipe @ io_write_nonblock.  This last time, my test case was attempting to enter a password into a password field after successfully entering a username.

```
uia.typeString('redacted@fake.com', '')

Result
Sending UIA command
uia.tapOffset('{:x 384, :y 479}')
2016-03-07 11:49:34 -0800 [RunLoop:debug]: 7:uia.tapOffset('{:x 384, :y 479}')
2016-03-07 11:49:34 -0800 [RunLoop:debug]: Trying write of command 7:uia.tapOffset('{:x 384, :y 479}') at index 7
2016-03-07 11:49:35 -0800 [RunLoop:debug]: validate index written for index 7 ok
Result
{"status"=>"success", "value"=>true, "index"=>7}
2016-03-07 11:49:39 -0800 [RunLoop:debug]: 8:uia.typeString('restrict1', '')
2016-03-07 11:49:39 -0800 [RunLoop:debug]: Trying write of command 8:uia.typeString('restrict1', '') at index 8

Sending UIA command

uia.typeString('redactedpassword1', '')

Errno::EPIPE: Broken pipe @ io_write_nonblock - /Users/dpbuild/.run-loop/results/2016-03-07_11-47-47/repl-cmd.pipe
./UIAutomation/features/tests/redacted.feature:31:in `And I enter "redactedpassword1" into the "Enter password" field'
```

On device, I see this after the previous test failed, which may be related:

```
Installing app via ideviceinstaller...
[Device] Install succeeded!

INFO: [2016-03-06 05:50:04 -0800] Edge server turned on
Exiting app...
  Scenario: Part 2, Rest of title redacted # ./features/tests/different_redacted.feature:72
      
      INFO: UIA Strategy: host
    And I find and tap the "CardName" card                                                  # features/step_definitions/bview_steps.rb:62
      Broken pipe - /Users/********/.run-loop/results/2016-03-06_05-50-11/repl-cmd.pipe (Errno::EPIPE)
      ./features/helpers/gestures.rb:263:in `touch'
      ./features/helpers/gestures.rb:236:in `wait_touch'
      ./features/helpers/bview.rb:180:in `tap_card'
```

**Comment by TeresaP** [comment]
specs:
    CFPropertyList (2.3.2)
    awesome_print (1.6.1)
    builder (3.2.2)
    calabash-cucumber (0.18.1)
      CFPropertyList
      awesome_print
      bundler (~> 1.3)
      cucumber
      edn (>= 1.0.6, < 2.0)
      geocoder (>= 1.1.8, < 2.0)
      httpclient (>= 2.3.2, < 3.0)
      json
      run_loop (>= 2.0.6, < 3.0)
      sim_launcher (~> 0.4.13)
      slowhandcuke (~> 0.0.3)
    command_runner_ng (0.1.0)
    cucumber (2.3.2)
      builder (>= 2.1.2)
      cucumber-core (~> 1.4.0)
      cucumber-wire (~> 0.0.1)
      diff-lcs (>= 1.1.3)
      gherkin (~> 3.2.0)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    cucumber-core (1.4.0)
      gherkin (~> 3.2.0)
    cucumber-wire (0.0.1)
    diff-lcs (1.2.5)
    edn (1.1.0)
    geocoder (1.3.1)
    gherkin (3.2.0)
    httpclient (2.7.1)
    json (1.8.3)
    multi_json (1.11.2)
    multi_test (0.1.2)
    rack (1.6.4)
    rack-protection (1.5.3)
      rack
    run_loop (2.0.7)
      CFPropertyList (~> 2.2)
      awesome_print (~> 1.2)
      command_runner_ng (>= 0.0.2)
      httpclient (~> 2.6)
      json (~> 1.8)
      thor (>= 0.18.1, < 1.0)
    sim_launcher (0.4.13)
      sinatra
    sinatra (1.4.7)
      rack (~> 1.5)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    slowhandcuke (0.0.3)
      cucumber
    thor (0.19.1)
    tilt (2.0.2)

**Comment by TeresaP** [comment]
Logs (https://github.com/calabash/run_loop/files/162032/2016-03-07_11-47-47.zip)

**Comment by TeresaP** [comment]
BTW when I went to rerun the test the next time, I saw Instruments was launched. I have never launched Instruments on that machine. Is it possible something Calabash is doing could launch the Instruments UI app?

**Comment by TeresaP** [comment]
Again, while running on simulator:
Errno::EPIPE: Broken pipe @ io_write_nonblock - /Users/dpbuild/.run-loop/results/2016-03-07_14-52-01/repl-cmd.pipe
./UIAutomation/features/helpers/gestures.rb:263:in `touch'
./UIAutomation/features/helpers/gestures.rb:236:in `wait_touch'
./UIAutomation/features/helpers/bview.rb:180:in `tap_card'
./UIAutomation/features/step_definitions/b_view_steps.rb:70:in `/I tap the "([^"]*)" card$/'
./UIAutomation/features/tests/redacted_download.feature:31:in `And I tap the "FREE" card'

**Comment by TeresaP** [comment]
[More logs](https://github.com/calabash/run_loop/files/162250/2016-03-07_14-52-01.zip)

**Comment by TeresaP** [comment]
And again on simulator:

When I swipe left on the screen 8 times
features/step_definitions/gestures_steps.rb:24
Broken pipe @ io_write_nonblock - /Users/dpbuild/.run-loop/results/2016-03-07_16-23-41/repl-cmd.pipe (Errno::EPIPE)
./UIAutomation/features/helpers/gestures.rb:141:in `flick'
./UIAutomation/features/helpers/gestures.rb:209:in `swipe_screen'
./UIAutomation/features/step_definitions/gestures_steps.rb:26:in `block (2 levels) in '
./UIAutomation/features/step_definitions/gestures_steps.rb:25:in `times'
./UIAutomation/features/step_definitions/gestures_steps.rb:25:in `/^I swipe (left|right|up|down) on the screen (\d+) times$/'
./UIAutomation/features/tests/redacted.feature:47:in `When I swipe left on the screen 8 times'

**Comment by jmoody** [comment]
@TeresaP What strategy are you using on the simulator?  :preferences?  If so, try going back to :host.

We've demonstrated that :shared_element has problems in several situations.

We've also demonstrated that :preferences is not stable enough for all gestures under iOS 9 - especially typing text.

I know that speed is an issue for you.  You might consider switching strategies on a per-Scenario basis.

**Comment by jmoody** [comment]
The CoreSimulator environment might be corrupt.

You can try to fix this with:

```
# CLI
$ run-loop simctl manage-processes

# Ruby
RunLoop::CoreSimulator.terminate_core_simulator_processes
```

And finally, try restarting your machine.

**Comment by TeresaP** [comment]
@jmoody We use :host for all cases currently. I provided a way for us to override it on a case-by-case basis but no tests are using it.

**Comment by TeresaP** [comment]
This seems to be happening on our lab machines as well as personal machines (I believe since updating to the latest run-loop). However, I will try the things you suggested.

**Comment by TeresaP** [comment]
@jmoody A reboot seems to have made things a lot happier. The `run-loop simctl manage-processes` command did not help though. Could be related to an issue with long-running processes? I will keep an eye out for more issues today. If I don't see anything, I'll close the bug and it can be reopened if others run into the issue.

**Comment by jmoody** [comment]
You might be bumping into this problem:

UIAutomation typeString throws a myriad of errors and is unreliable.  Calabash does its best to shield users from these errors. Unfortunately, the fixes do not work and cause problems.

Can you try: 

```
touch(< the text field or text view >)
wait_for_keyboard

# Option 1: Use UIATextField/TexView .setValue() 
# May or may not trigger delegate methods.
fast_enter_text("text to type")

# Option 2.
uia("UIATarget.localTarget().frontMostApp().keyboard().typeString('text to type')")
```

**Comment by TeresaP** [comment]
Still seeing issues. It happens with swipe gestures too. I'm going to roll back to a previous version and see if it helps.

**Comment by TeresaP** [comment]
@jmoody 

Does https://github.com/calabash/run_loop/blob/d4eb38ec9df86fceb998a1f1eaf8944574355470/lib/run_loop/fifo.rb#L17 need something like this added?

rescue Errno::EPIPE
      pipe_io.close
      retry
end

**Comment by TeresaP** [comment]
@jmoody this seems to be the winner. I'll see if I can create a PR with the change so it can be tested on your end.
