### ISSUE TITLE
Run_loop failed to validate index written for index 1 (1st step of any scenario)

### ISSUE THREAD

**Issue by SergiyBeno** [calabash/run_loop#475]
Hi guys :)
Today I have finally updated my working environment (calabash-cucumber and run_loop gems) and now it looks like following:

- OS X El Capitan 10.11.5 
- iOS SDKs: iOS 9.3 -sdk iphoneos9.3
- xcode installation location: /Applications/Xcode.app/Contents/Developer
- xcode version: Xcode 7.3.1 Build version 7D1014
- calabash version 0.19.1
- run_loop (2.1.3)
- curl http://localhost:37265/version

`{"device_family" : "iPhone",
"outcome" : "SUCCESS",
"server_port" : 37265,
"simulator_device" : "iPhone",
"simulator" : "CoreSimulator 209.19 - Device: iPhone 5s - Runtime: iOS 9.3 (13E230) - DeviceType: iPhone 5s",
"app_name" : "******",
"app_version" : "1000",
"screen_dimensions" : {"native_scale" : 2,"sample" : 1,"height" : 1136, "width" : 640,"scale" : 2},
"git":{"revision":"*****","remote_origin" : "*****","branch" : "*****"},
"device_name" : "iPhone Simulator", "4inch" : true, 
"app_id" : "*****",
"form_factor" : "iphone4in",
"system" : "x86_64",
"version" : "0.19.1",
"iOS_version" : "9.3",
"short_version_string" : "*****",
"ios_version" : "9.3",
"iphone_app_emulated_on_ipad" : false,
"model_identifier" : "iPhone6,1",
"app_base_sdk" : "iphonesimulator9.3"}`

The problem was discovered when I tried to run a scenario like this one:

Scenario: test scenario
  Given the app is running
  * I navigate to the "Home" screen
  * I navigate to the "Home" screen
  * I navigate to the "Home" screen
  * I navigate to the "Home" screen
  * I navigate to the "Home" screen

When calabash reaches 1st step it presses on specific button (home button) and hangs for ~ 15 seconds.
After 1st step has been executed and we passed through that nasty timeout (~ 15 sec) further steps will be executed smoothly (without any delays - note steps are identical)
Here is output received using DEBUG=1 argument:

2016-06-16 16:41:40 +0300 [RunLoop:debug]: xcrun instruments -w C2A35D1F-E56D-4DE2-9E06-2D07EC8F5C4D -D /Users/Sergiy/.run-loop/results/2016-06-16_16-40-56/trace -t Automation com.****** -e UIARESULTSPATH /Users/Sergiy/.run-loop/results/2016-06-16_16-40-56 -e UIASCRIPT /Users/Sergiy/.run-loop/results/2016-06-16_16-40-56/_run_loop.js >& /Users/Sergiy/.run-loop/results/2016-06-16_16-40-56/run_loop.out
2016-06-16 16:41:41 +0300 [RunLoop:debug]: Preparation took 46.51703 seconds
2016-06-16 16:41:46 +0300 [RunLoop:debug]: Launching took 5.362865 seconds
DEBUG: It took 51.880043 seconds to launch the app
DEBUG: Trying to connect to Calabash Server: 1 of 10
DEBUG: Connected to Calabash Server on try: 1 of 10
DEBUG: Trying to connect to Calabash Server: 1 of 10
DEBUG: Connected to Calabash Server on try: 1 of 10
    Given the app is running                   # calabash-cucumber-0.19.1/features/step_definitions/calabash_steps.rb:4
Sending UIA command
uia.tapOffset('{:x 35.5, :y 543.5}')
2016-06-16 16:41:59 +0300 [RunLoop:debug]: 1:uia.tapOffset('{:x 35.5, :y 543.5}')
2016-06-16 16:42:00 +0300 [RunLoop:debug]: Trying write of command 1:uia.tapOffset('{:x 35.5, :y 543.5}') at index 1
**2016-06-16 16:42:10 +0300 [RunLoop:debug]: validate index written for index 1 failed. Retrying.
2016-06-16 16:42:10 +0300 [RunLoop:debug]: Trying write of command 1:uia.tapOffset('{:x 35.5, :y 543.5}') at index 1
2016-06-16 16:42:21 +0300 [RunLoop:debug]: validate index written for index 1 failed. Retrying.
2016-06-16 16:42:21 +0300 [RunLoop:debug]: Failing...Raising RunLoop::WriteFailedError
2016-06-16 16:42:21 +0300 [RunLoop:info]: Core.write_request failed: Trying write of command 1:uia.tapOffset('{:x 35.5, :y 543.5}') at index 1. Attempting recovery...
2016-06-16 16:42:21 +0300 [RunLoop:info]: Attempting read in case the request was received... Please wait (25)...
2016-06-16 16:42:23 +0300 [RunLoop:info]: Did read response for interrupted request of index 1... Proceeding.**
Result
{"status"=>"success", "value"=>true, "index"=>1}
    * I navigate to the "Home" screen          # features/step_definitions/general_steps.rb:226
Sending UIA command
uia.tapOffset('{:x 35.5, :y 543.5}')
2016-06-16 16:42:24 +0300 [RunLoop:debug]: 2:uia.tapOffset('{:x 35.5, :y 543.5}')
2016-06-16 16:42:24 +0300 [RunLoop:debug]: Trying write of command 2:uia.tapOffset('{:x 35.5, :y 543.5}') at index 2
2016-06-16 16:42:24 +0300 [RunLoop:debug]: validate index written for index 2 ok
Result
{"status"=>"success", "value"=>true, "index"=>2}
    * I navigate to the "Home" screen          # features/step_definitions/general_steps.rb:226
Sending UIA command
uia.tapOffset('{:x 35.5, :y 543.5}')
2016-06-16 16:42:25 +0300 [RunLoop:debug]: 3:uia.tapOffset('{:x 35.5, :y 543.5}')
2016-06-16 16:42:25 +0300 [RunLoop:debug]: Trying write of command 3:uia.tapOffset('{:x 35.5, :y 543.5}') at index 3
2016-06-16 16:42:26 +0300 [RunLoop:debug]: validate index written for index 3 ok
Result
{"status"=>"success", "value"=>true, "index"=>3}
    * I navigate to the "Home" screen          # features/step_definitions/general_steps.rb:226
Sending UIA command
uia.tapOffset('{:x 35.5, :y 543.5}')
2016-06-16 16:42:26 +0300 [RunLoop:debug]: 4:uia.tapOffset('{:x 35.5, :y 543.5}')
2016-06-16 16:42:26 +0300 [RunLoop:debug]: Trying write of command 4:uia.tapOffset('{:x 35.5, :y 543.5}') at index 4
2016-06-16 16:42:27 +0300 [RunLoop:debug]: validate index written for index 4 ok
Result
{"status"=>"success", "value"=>true, "index"=>4}
    * I navigate to the "Home" screen          # features/step_definitions/general_steps.rb:226
Sending UIA command
uia.tapOffset('{:x 35.5, :y 543.5}')
2016-06-16 16:42:28 +0300 [RunLoop:debug]: 5:uia.tapOffset('{:x 35.5, :y 543.5}')
2016-06-16 16:42:28 +0300 [RunLoop:debug]: Trying write of command 5:uia.tapOffset('{:x 35.5, :y 543.5}') at index 5
2016-06-16 16:42:28 +0300 [RunLoop:debug]: validate index written for index 5 ok
Result
{"status"=>"success", "value"=>true, "index"=>5}

Can you tell me how can I overcome this nasty timeout after 1st step ?

**Comment by SergiyBeno** [comment]
I googled for a little bit and found similar issue https://groups.google.com/forum/?fromgroups#!topic/calabash-ios/VLoPSK42Ihs
But I don't see any progress upon it

**Comment by jmoody** [comment]
Are you trying to touch a UITabBarButton?

https://github.com/calabash/calabash-ios/issues/304

Can you paste your launch hooks?  Specifically, I am looking to see if you are using a non-default `:uia_strategy` in your options.

**Comment by SergiyBeno** [comment]
@jmoody Thank you for your fast reply!

1 - no this is simple button. And if I try to perform tap gesture upon it via calabash-ios console everything will be just great:

```
calabash-ios 0.19.1> touch("view:'UIButton' marked:'Home tab'")
[
    [0] {
                          "id" => nil,
                 "description" => "<UIButton: 0x7fd823401f40; frame = (11 0; 49 49); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x7fd8229e66d0>>",
                       "label" => "Home tab",
                       "frame" => {
                 "y" => 0,
                 "x" => 11,
             "width" => 49,
            "height" => 49
        },
        "accessibilityElement" => true,
                       "value" => nil,
                       "alpha" => 1,
                     "enabled" => true,
                     "visible" => 1,
                    "selected" => false,
                       "class" => "UIButton",
                        "rect" => {
                   "y" => 519,
            "center_x" => 35.5,
            "center_y" => 543.5,
                   "x" => 11,
               "width" => 49,
              "height" => 49
        }
    }
]

```
2 - Launch hooks ? Yes, no problem:

```
require 'calabash-cucumber/launcher'

Before do |scenario|
  @calabash_launcher = Calabash::Cucumber::Launcher.new
  options = {
      :uia_strategy => :host,
      :timeout => 600
  }
  target_is_simulator = @calabash_launcher.simulator_target?
  target_is_physical_device = @calabash_launcher.device_target?
  scenario_tags = scenario.source_tag_names
  if scenario_tags.include?('@reinstall')
    ENV['RESET_BETWEEN_SCENARIOS'] = '1' if target_is_simulator
    if target_is_physical_device
      system('ios-deploy --uninstall_only --bundle_id com.******')
      system('ios-deploy --justlaunch --debug --bundle ~/cal-ios-autt/******.app')
    end
  else
    ENV['RESET_BETWEEN_SCENARIOS'] = '0' if target_is_simulator
  end
    @calabash_launcher.relaunch(options)
end

AfterStep do |scenario|
end

After do |scenario|
  calabash_exit unless @calabash_launcher.calabash_no_stop?
end

```

**Comment by SergiyBeno** [comment]
@jmoody Thank you again for this tip: important update about hooks - this issue is applicable only for **:uia_strategy => :host** 
Tested with **:uia_strategy => :preferences, :uia_strategy => :shared_element** and couldn't reproduce this issue.
Question - what's wrong with **:uia_strategy => :host** ?

**Comment by jmoody** [comment]
> which strategy

Use the default. Put another way, don't set the `:uia_strategy` option.

> blocking

Is there something in your app that is blocking the main thread?  Like loading an analytics library?  I am guessing that your app is not ready for interaction directly after launch.  Try adding a small sleep, say 5 seconds, after the first query succeeds and before touching the button.  Increase the sleep until 15 seconds if you still see the UIA timeout.

**Comment by SergiyBeno** [comment]
> Is there something in your app that is blocking the main thread?

Need to talk about that with iOS dev team - cannot say for sure

> Use the default. Put another way, don't set the :uia_strategy option.

Ok, accordingly to your advice I have completely removed _:uia_strategy_ option from the hooks but I still observe that by default it again start using **:uia_strategy => :host** and again it causes the same issue that I have already described above.

> Increase the sleep until 15 seconds if you still see the UIA timeout.

Yes, I have done exactly as you suggested - added new static wait timeout after the first successful query. It helped only when I reached 15 sec duration. But that is too "expensive" for me - I have too many scenarios.  

> Which strategy is more preferable at this moment ? :uia_strategy => :preferences, :uia_strategy => :shared_element

So, can you please tell me your thoughts about this question ?

**Comment by SergiyBeno** [comment]
Hi @jmoody 
I asked our iOS dev team about processes that might block main thread. Their answer is "hell no, we don't have anything that could cause that issue" and I strongly believe them cause they are real professionals. 
They helped me to investigate this issue deeper and found this older issue https://github.com/calabash/calabash-ios/issues/997
I reused some thoughts from there, especially about "LaunchControl" module and rewrote my launch.rb file accordingly to your example (https://github.com/calabash/ios-smoke-test-app/blob/master/CalSmokeApp/features/support/01_launch.rb)
But the result still the same - default **:host** :uia_strategy causes my issue. Once I switch it to **:preferences or :shared_element** everything goes smoothly.

**Comment by jmoody** [comment]
`:preferences` or `:shared_element` may or may not work for you in the long run - they are both very unstable.  `:preferences` is not available on iOS 8.

**Comment by SergiyBeno** [comment]
Today had a chance to check out calabash version 0.19.2. I was hoping that it might be a solution for my issue but still the same issue after each 1st scenario step. As a temporary solution I did a rollback back to calabash/run_loop 0.18.2/2.1.1 and everything is running smoothly again as it should be. 
@jmoody I know that 0.19 calabash contains a lot of significant changes and etc. but maybe you can come up with some astute solution ? Your help is really highly appreciated. Thank you advance.

**Comment by jmoody** [comment]
```
:uia_strategy => :host,
       :timeout => 600
```

`:timeout` here controls the amount of time calabash should wait for the embedded server to respond to _http requests_.  Remove the `:timeout` setting unless you can see _http requests_ timing out - this almost never happens

Your problem is that the communication with UIAutomation is timing out on the first gesture.  From you description, the gesture eventually succeeds, but you want to try to make it faster.  I have looked at the code that handles the interrupt read timeout.  There is no variable or option publicly exposed to control default 25 seconds wait-before-retry.  Can you create a GitHub issue "publicly expose UIA retry variables" and link to this issue?

You can try `:shared_element`, but there are some limitations (stops working after the app has been sent to the background).

As for the cause of this, does your app do a lot of logging with NSLog at launch?  This can block UIAutomation (known bug).

**Comment by SergiyBeno** [comment]
Hi again @jmoody 
Finally I got my issue fixed. I'm embarrassed to say but the reason was old spike that I took from here calabash/calabash-ios#961
I simply forgot to remove it after gem upgrade. Once I removed that stub - error message disappeared. Sorry for bothering you for such a long time 😊
