### ISSUE TITLE
Default device interfering with Simulator lookup

### ISSUE THREAD

**Issue by umara123** [calabash/run_loop#480]
With run_loop 2.0.6 I start my tests without issue using the following command:

```
APP=MyApp.app && APP_BUNDLE_PATH=$APP && DEVICE_TARGET=SIMULATOR_UDID bundle exec cucumber
```

After I updated to run_loop 2.1.3 I get the following error:

```
Could not find a device with a UDID or name matching 'iphone' (ArgumentError)
/run_loop/lib/run_loop/device.rb:128:in `device_with_identifier'
/run_loop/lib/run_loop/device.rb:162:in `detect_device'
/run_loop/lib/run_loop/core.rb:67:in `run_with_options'
/run_loop/lib/run_loop.rb:107:in `run'
/.gem/ruby/2.1.1/gems/calabash-cucumber-0.18.0/lib/calabash-cucumber/launcher.rb:718:in `block in new_run_loop'
/.gem/ruby/2.1.1/gems/calabash-cucumber-0.18.0/lib/calabash-cucumber/launcher.rb:716:in `times'
/.gem/ruby/2.1.1/gems/calabash-cucumber-0.18.0/lib/calabash-cucumber/launcher.rb:716:in `new_run_loop'
/.gem/ruby/2.1.1/gems/calabash-cucumber-0.18.0/lib/calabash-cucumber/launcher.rb:584:in `Before'
```

I set a breakpoint at `run_loop/lib/run_loop/core.rb @ line 67` and inspected the `options` variable:

```
{:launch_method=>:instruments,
 :reset=>true,
 :bundle_id=>”my_apps_bundle_id”,
 :device=>"iphone",
 :no_stop=>false,
 :no_launch=>false,
 :sdk_version=>nil,
 :relaunch_simulator=>true,
 :launch_retries=>5,
 :udid=>"SIMULATOR_UDID",
 :device_target=>"SIMULATOR_UDID",
 :uia_strategy=>:host,
 :sim_control=>#<RunLoop::SimControl:0x007fcab71f8c20 @xcode=#<Xcode 7.3.1>>,
 :instruments=>#<Instruments 7.3>,
 :xcode=>#<Xcode 7.3.1>,
 :app=>”path-to-my-cal-app.app"}
```

So my SIMULATOR_UDID is coming through but it appears as though a default value set by calabash in `/gems/calabash-cucumber-0.18.0/lib/calabash-cucumber/launcher.rb:659` of `:device=>"iphone"` is overriding it, and therefore the list of my installed simulators is being searched for 'iphone' instead of the actual simulator UDID I passed in.

I've worked around by running the tests with:

```
APP=MyApp.app && APP_BUNDLE_PATH=$APP && DEVICE_TARGET=SIMULATOR_UDID && DEVICE=SIMULATOR_UDID bundle exec cucumber
```

**Comment by jmoody** [comment]
Please update to latest version of Calabash iOS and run-loop.

```
DEVICE_TARGET=SIMULATOR_UDID
```

You need to use a concrete UDID, like `05B84CAA-E440-45F3-BB21-FAA0215C69E1`.

Did you substitute a UDID for `SIMULATOR_UDID` for the purposes of reporting?

The `DEVICE` variable is ignored for iOS < 7.

```
APP=MyApp.app && APP_BUNDLE_PATH=$APP
```

These values are synonymous: they indicate the same thing.  Use:

```
APP=$APP
```

`APP_BUNDLE_PATH` and `BUNDLE_ID` support will be removed at some point.

**Comment by jmoody** [comment]
Closing issue.  Please comment if my suggestion did not fix your issue.
