### ISSUE TITLE
Not getting calabash elements 

### ISSUE THREAD

**Issue by bansalvarsha** [calabash/run_loop#519]
Hi @jmoody, 

I am facing some issue related to calabash elements. When I execute the command 
[admin@calabash-sandbox]$ calabash-ios console
it is giving me some information instead of calabash elements. 
![image](https://cloud.githubusercontent.com/assets/17331728/18080658/0ddecfac-6eb4-11e6-8d09-14f76a04ff6b.png)

Server is working properly from xcode and I am able to launch the application in simulator using cucumber command. 

Please help and take me out from this problem.

Thanks

**Comment by jmoody** [comment]
@bansalvarsha Everything in that screenshot is normal.

What is the problem?

**Comment by bansalvarsha** [comment]
hi @jmoody,

I have resolved the above problem. Can you please just tell me that is it possible to run the calabash scripts, if I have only ipa file not xcode project of any application?

**Comment by jmoody** [comment]
It is not possible.  The calabash.framework must be built into your application.

**Comment by bansalvarsha** [comment]
I got it. Resolved my problem few days back. Thanks for the reply.
