### ISSUE TITLE
Location of dependencies, e.g. DeviceAgent.iOS and iOSDeviceManager, are not given

### ISSUE THREAD

**Issue by sleekweasel** [calabash/run_loop#540]
Although FBSimulatorControl is easily found with a trivial Google at https://github.com/facebook/FBSimulatorControl

the other two aren't, and I wasn't able to find references to them beyond their name, and a reference at nuget.org which comes to a broken link (in the case of DeviceAgent.IOS) and multiple unrelated projects for iOSDeviceManager.

Could the documentation give URLs, and maybe name the authors or companies involved?

The reason I'm interested: we currently use a hybrid approach to run single-device tests in parallel on paired Calabash instances and iOS simulators, all on one desktop, and we want to understand the new iOSDeviceManager-based architecture, to see whether we can use that instead. (In particular, whether we need multiple iOSDeviceManagers on different ports to work with multiple simulators and instances of Calabash.)

Thanks

**Comment by jmoody** [comment]
* All binaries are in lib/run_loop/device_agent/
* We use our own fork of FBSimulatorControl [calabash/FBSimulatorControl](https://github.com/calabash/FBSimulatorControl)
* DeviceAgent.iOS is a private repo that we plan to open source soon. This could change.
* iOSDeviceManager is a private repo - AFAIK, we do not have plans to open source this tool.  This could change.

> iOSDeviceManager

Multiple instances can be run at once.

> DeviceAgent.iOS

This uses port 27753 for HTTP calls.

The port can be overridden using an environment variable. `ENV["DEVICE_AGENT_URL"]`.

**Comment by sleekweasel** [comment]
That's very helpful information; we'll continue trying to get our parallel tests working with your supplied binaries then.

Many thanks!

**Comment by sleekweasel** [comment]
@jmoody Hi, we've tried setting DEVICE_AGENT_URL but it doesn't seem to be working for us:

$ DEVICE_AGENT_URL=27756  /Users/s/.rvm/gems/ruby-2.1.5/gems/run_loop-2.2.0/lib/run_loop/device_agent/bin/iOSDeviceManager start_test --device-id 19795CFE-B684-428C-AF8E-A2B702EF24CA
$ curl -X GET '-H "Content-Type: application/json"' http://127.0.0.1:27756/1.0/health

And lsof |grep :277 shows 27753 being used.

 Is this rather DEVICE_AGENT_URL=http://localhost:1234 or DEVICE_AGENT_PORT=1234?

**Comment by jmoody** [comment]
```
DEVICE_AGENT_URL=http://127.0.0.1:<port>
```

I am afraid I cannot give you more support. You are on the right track.

**Comment by jmoody** [comment]
Override the `:port` option.

https://github.com/calabash/run_loop/blob/develop/lib/run_loop/device_agent/client.rb#L33

**Comment by jmoody** [comment]
My mistake.  There is no way to change this port number on the DeviceAgent itself.

**Comment by sleekweasel** [comment]
Ah, that's a nuisance. Might have to resort to some binary hacking. Haven't done machine code for a while!

Thanks for the clarification.

**Comment by jmoody** [comment]
Tracking this issue in #541
