### ISSUE TITLE
RuntimeError: Expected instruments to report an Automation tracetemplate.

### ISSUE THREAD

**Issue by sglet** [calabash/run_loop#547]
Hi,

Since we upgraded to Xcode 8 and Mac OS Sierra we cannot run our tests from RubyMine 8. As soon as we do we get in the error message "RuntimeError: Expected instruments to report an Automation tracetemplate".

xcrun xcodebuild -version
Xcode 8.0
Build version 8A218a

xcrun instruments -s templates

Known Templates:
"Activity Monitor"
"Allocations"
"Blank"
"Cocoa Layout"
"Core Animation"
"Core Data"
"Counters"
"Energy Log"
"File Activity"
"Leaks"
"Metal System Trace"
"Network"
"OpenGL ES Analysis"
"System Trace"
"System Usage"
"Time Profiler"
"Zombies"

Ruby version: ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin15.5.0]

gem list

*** LOCAL GEMS ***

activesupport (4.2.6)
awesome_print (1.7.0)
backports (3.6.8)
bigdecimal (1.2.7, 1.2.0)
builder (3.2.2)
bundler (1.13.2)
bundler-unload (1.0.2)
calabash-cucumber (0.20.0)
CFPropertyList (2.3.3)
claide (1.0.0)
clipboard (1.1.1)
cocoapods (1.0.1)
cocoapods-core (1.0.1)
cocoapods-deintegrate (1.0.1)
cocoapods-downloader (1.1.1)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.0.0)
cocoapods-try (1.1.0)
colored (1.2)
command_runner_ng (0.1.0)
concurrent-ruby (1.0.2)
cucumber (2.4.0)
cucumber-core (2.0.0, 1.5.0)
cucumber-wire (0.0.1)
diff-lcs (1.2.5)
edn (1.1.1)
escape (0.0.4)
executable-hooks (1.3.2)
fourflusher (1.0.1, 0.3.2)
fuzzy_match (2.1.0, 2.0.4)
gem-wrappers (1.2.7)
geocoder (1.4.0)
gherkin (4.0.0)
httpclient (2.8.2.4)
i18n (0.7.0)
io-console (0.4.6, 0.4.2)
json (2.0.2, 1.8.3, 1.7.7)
minitest (5.9.1, 4.3.2)
molinillo (0.5.1, 0.4.5)
multi_json (1.12.1)
multi_test (0.1.2)
nap (1.1.0)
netrc (0.11.0, 0.7.8)
power_assert (0.3.1)
psych (2.1.1, 2.0.0)
rake (11.3.0, 0.9.6)
rdoc (4.2.2, 4.0.0)
rubygems-bundler (1.4.4)
run_loop (2.2.1)
rvm (1.11.3.9)
slowhandcuke (0.0.3)
test-unit (3.2.1, 2.0.0.0)
thor (0.19.1)
thread_safe (0.3.5)
tzinfo (1.2.2)
xcodeproj (1.3.1)

What could be the issue ?

Thanks
Simon Glet

**Comment by jmoody** [comment]
>  "RuntimeError: Expected instruments to report an Automation tracetemplate".

There is no Automation tracetemplate in Xcode 8.  It has been removed.

> RubyMine

RubyMine run configurations can be quite complex and I cannot help you debug this issue.  My best guess is that you _think_ you are using run-loop 2.2.1 in RubyMine, but you are actually using some other version. 

I see you are using Apple's system ruby.  From recent experience, this will not work if you run from the command line starting with Xcode 8 - you must switch to a managed ruby or use the Calabash sandbox.

https://github.com/calabash/calabash-ios/wiki/Ruby-on-MacOS

**Comment by sglet** [comment]
Ah well ... Anyone thinking of upgrading to Xcode 8 and Mac OS Sierra, beware !!!

I will continue searching for a solution but as far as I can gather, updating to from Ruby 2.0.0p247 seems the way to go. Now I just have to figure out how update BigDecimal. Yes BigDecimal 1.2.0 cannot install because of a bug but installing 1.2.6 doesn't allow to update my gems ... Args, dependencies ...

Thanks for your input.

I will continue my quest ...

**Comment by jmoody** [comment]
> Anyone thinking of upgrading to Xcode 8 and Mac OS Sierra, beware !!!

This is not a helpful statement. 

There have been the usual problems associated with any major Xcode/iOS/MacOS update.  In fact, this transition has been better than previous years.

We have been recommending that users switch from the Apple system ruby to a managed ruby for over 2 years.

**Comment by sglet** [comment]
Thank you for pointing out the unhelpful statement I really appreciate it. We will be looking into the managed ruby option in order to hopefully mitigate the effects of the next Apple update.

Cheers
