### ISSUE TITLE
Using the dismiss-springboard-alerts Function?

### ISSUE THREAD

**Issue by DragonClub** [calabash/run_loop#602]
What happens to the post-forwarding rule for the dismiss-springboard-alerts url in the DeviceAgent?

And what happens to the post rule that can get the element through the query and touch it?

**Comment by jmoody** [comment]
I am sorry, what do you mean?

**Comment by DragonClub** [comment]
dismiss-springboard-alerts function. .
post value . .?

**Comment by DragonClub** [comment]
I want to know the value of dismiss-springboard-alerts.(post request rule. .)

**Comment by DragonClub** [comment]
curl -v -X POST -d '{???:???}' http://0.0.0.0:27753/1.0/dismiss-springboard-alerts

???:??? =>

**Comment by jmoody** [comment]
The body is empty.

You should not be calling this route manually.

It is called automatically in the context of querying and gestures.

**Comment by jmoody** [comment]
> touch not working

What is the error?
