### ISSUE TITLE
Add Korean Springboard alert definitions

### ISSUE THREAD

**Issue by DragonClub** [calabash/run_loop#609]
jmoody .. Thank you every time..

I want to update the alert definition of DeviceAgent.

My iPhone is using Korean language.
So the springboard alert is not dismissed.
Undefined languages (for example, Korean, Japanese, Chinese)

Can I manually update the DeviceAgent's alert definitions?

Is it possible?

**Comment by jmoody** [comment]
> Can I manually update the DeviceAgent's alert definitions?

No.  DeviceAgent is not open source (yet).

I will try to get someone assigned to this. 

For the buttons, we need to know which button means "Accept", "OK", or "Allow".   Can you help us?

* "허용 안 함" => Do not allow, Decline, No?
* "허용" => Allow, OK, Accept?

The health kit example is complicated.

![image](https://cloud.githubusercontent.com/assets/466104/23891751/1d35a326-0898-11e7-9a01-6142fb8e3294.png)

Can you write the text for "All allow categories", "Cancel", and "Done"?

**Comment by SeongWonsang** [comment]
Hi everyone. I have the same issue as above.
Jmoody, I can help you about the your korean questions.
However, I know only part of the alert message (which comes from the iPhone).
(I think, you already know many kinds of alert messages.)
If possible, please send me your own alert message list (in English) and we will reply to you with your message in Korean.

Thanks.

**Comment by jmoody** [comment]
@SeongWonsang 

> I can help you about the your Korean questions.

Thanks!

>  please send me your own alert message list

I have the Korean text of most alerts.

I am missing:

* Apple Push Notifications
* Microphone (can only be generated on a physical device)
* Enable an app to connect to Bluetooth (can only be generated on a physical device) - this is _not_ the "Turn on Bluetooth in Settings" alert.

> Can you write the text for "All allow categories", "Cancel", and "Done"?

I cannot copy and paste the text from the screenshot or the simulator.  Can you provide the text for those 3 ^ phrases/words?

**Comment by SeongWonsang** [comment]
All allow categories: 모든카테고리 켜기

* but below text is can find English version. (I guess .. )
  So, can you send me a picture about the below text

Cancel: 취소
Done: 완료

**Comment by jmoody** [comment]
I have circled the text that needs translation or physical text in the following screenshots.

![image](https://cloud.githubusercontent.com/assets/466104/23941785/7d89b474-096a-11e7-83ef-8b920baf26b7.png)

![image](https://cloud.githubusercontent.com/assets/466104/23941847/abd40744-096a-11e7-91dd-5fae0f6e0bac.png)

Thanks!!!

**Comment by SeongWonsang** [comment]
허용 안함: Don't Allow
허용: Allow
모든 카테고리 켜기: All allow categories
취소: Cancel

Thanks.

**Comment by jmoody** [comment]
Available in run-loop 2.4.0
