### ISSUE TITLE
How do I run the physical home button?

### ISSUE THREAD

**Issue by DragonClub** [calabash/run_loop#612]
Hi. jmoody.

How do I run the physical home button?

curl -v -X POST -d '{""}' http://0.0.0.0:27753/1.0/home

The home button is performed, but the response http code shows a 404 error result.

It worked fine on iOS 10.2.1, but it does not work on iOS 10.3.

Is there any other way?

Another problem is

IOS 10.3 DeviceAgent is running but it is down (crash).

**Comment by jmoody** [comment]
Touching the home button is not supported.
