### ISSUE TITLE
Turn off keyboard auto-correct, capitalization, and completion on Simulators

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#64]
https://groups.google.com/forum/#!topic/calabash-ios/xlc9YPKev0M

**Comment by fabb** [comment]
I tried by inserting the following code in `support/01_launch.rb` directly after the line `@calabash_launcher.relaunch`.

```
    device_target = ENV['DEVICE_TARGET']
    if !device_target.nil? && device_target.downcase.include?('simulator')
      sim_uuid = `instruments -s devices | grep "#{device_target}" | egrep -o '\\[.*\\]' | tr -d '[]'`.chomp
      unless sim_uuid.nil?
        `defaults write ~/Library/Developer/CoreSimulator/Devices/#{sim_uuid}/data/Library/Preferences/com.apple.Preferences.plist KeyboardAutocapitalization -bool NO`
        `defaults write ~/Library/Developer/CoreSimulator/Devices/#{sim_uuid}/data/Library/Preferences/com.apple.Preferences.plist KeyboardAutocorrection -bool NO`
        `defaults write ~/Library/Developer/CoreSimulator/Devices/#{sim_uuid}/data/Library/Preferences/com.apple.Preferences.plist KeyboardCheckSpelling -bool NO`
        `defaults write ~/Library/Developer/CoreSimulator/Devices/#{sim_uuid}/data/Library/Preferences/com.apple.Preferences.plist KeyboardPrediction -bool NO`
      end
    end
```

Unfortunately the simulator ignores these settings, even if I do it manually in the simulator Settings. When I type something in a text field, it gets automatically replaced. Any idea why?

**Comment by swolfekabaminc** [comment]
Ah, this is happening when I set a breakpoint and start interacting manually with my app. So I start the app under automation, get to the breakpoint, and start entering text manually in fields. It senses I'm using my hardware keyboard. Subsequent automation runs keep the keyboard suppressed and this breaks the test :broken_heart: 

Any way to explicitly call the keyboard to come back ?

**Comment by fabb** [comment]
The native UI tests in Xcode 7 beta 4 have fixed this issue:
> Unpredictable results caused by Auto-correct in UI tests that type text have been fixed. (21106884)

Maybe now there is a programmatic way to disable auto-correct also when using calabash?

**Comment by jmoody** [comment]
@fabb Thanks for the update.  We'll have to dig into the Xcode 9 CoreSimulator plists. 

Calabash can turn off/on autocorrect, but it can't turn on autocorrect on the XTC.

* https://github.com/calabash/ios-smoke-test-app/blob/master/CalSmokeApp/features/keyboard.feature
* https://testcloud.xamarin.com/test/calsmoke-cal_f972e655-4b34-4ea5-a835-e484906f9fba/

**Comment by jmoody** [comment]
I believe this is fixed.
