### ISSUE TITLE
iOS 11 - iOSDeviceManager unable to install DeviceAgent on the device

### ISSUE THREAD

**Issue by skhand001** [calabash/run_loop#657]
Test execution stops after 2-3 hours on iOS 11 devices. The same setup works fine for iOS 10 devices.
gems being used - 
run_loop - 2.6.1/2.6.0/2.5.4
calabash-cucumber - 0.21.1/0.20.5
cucumber - 3.0.0.pre.2
Xcode - 9
iOS - 11.0/11.0.1/11.0.2

Below is the error message - 
![screen shot 2017-10-10 at 9 24 28 am](https://user-images.githubusercontent.com/32458501/31464491-c23b39d2-ae9f-11e7-866e-7acdad6e6dfb.png)

Only after the restarting the device, the tests can be executed further.

After further debugging the issue, seems like iOSDeviceManager is unable to install/launch device agent app on the device. Unable to view the source code for iOSDeviceManager, hence not able to debug further.

**Comment by skhand001** [comment]
@jmoody - Can you please suggest any ideas in debugging further as we have no access to iOSDeviceManager?

**Comment by jmoody** [comment]
Fixed in 2.6.2
