### ISSUE TITLE
Possibility to ignore system level alert views

### ISSUE THREAD

**Issue by JaniJegoroff** [calabash/run_loop#66]
System level alert views are dismissed automatically by default (which is very convenient). However, some rare cases it would be nice to tell Calabash not to dismiss these alert views, like APNS alerts.

See discussion for reference: https://github.com/calabash/calabash-ios/issues/585#issuecomment-61088240

**Comment by jmoody** [comment]
Needs something like #106

**Comment by TitouanVanBelle** [comment]
Any update on this?

**Comment by jmoody** [comment]
No direct progress, but this **Extract Logger and onAlert to a single JavaScript file using erb templates** #261 gives us an opportunity to add support.

I would be more than happy to review pull-requests and give some guidance.

**Comment by jmoody** [comment]
There is a DeviceAgent API for turning off automatic dismissal of alerts.
