### ISSUE TITLE
Not able to install DeviceAgent- No valid iOSDeveloperIdentities found on system

### ISSUE THREAD

**Issue by sankalpanand** [calabash/run_loop#672]
**xcrun xcodebuild -version**: 9.2
**run_loop**: 2.6.4
**calabash-ios version**: 0.20.5
**iOS version**: 11.2.6

**Command**- `/Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.4/lib/run_loop/device_agent/bin/iOSDeviceManager install /Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.4/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id 61b08575d55927c0dd0b9192e37a2c1f421cd000`

**Output:**
```
*** Terminating app due to uncaught exception 'CBXException', reason: 'Unable to find appropriate codesign identity for device 61b08575d55927c0dd0b9192e37a2c1f421cd000 / app com.apple.test.DeviceAgent-Runner combo'
```

**Output of tail -F ~/.calabash/iOSDeviceManager/logs/current.log**
```
2018-03-20 16:46:04.676 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d --entitlements :- /Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.4/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2018-03-20 16:46:05.171 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d --entitlements :- /Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.4/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2018-03-20 16:46:05.258 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security find-identity -v -p codesigning
2018-03-20 16:46:05.466 ERROR ConsoleWriter:32 | No valid iOSDeveloperIdentities found on system.
```

However, the profile exists in the `/Users/testmaskin/Library/MobileDevice/Provisioning Profiles` directory as well as the device UDID exists in that profile.

Not sure what I'm missing here. I have a bunch of such test devices attached to their own Mac Mini hosts. Each of those setup are exhibiting this problem. So I'm sure its not because of a faulty device. Any help is appreciated.

**Comment by jmoody** [comment]
You can run the command yourself:

```
 $ /usr/bin/xcrun security find-identity -v -p codesigning
```

Are any identities found?

**Comment by sankalpanand** [comment]
@jmoody Yes, I am able to find the identities. 
```
$ /usr/bin/xcrun security find-identity -v -p codesigning
1) 95CC7E649668236B68C7D309A07AAC5E3C9B409B "iPhone Distribution: Polly Lal (***********)"
     1 valid identities found
```

**Comment by jmoody** [comment]
I believe you will need a developer certificate not a distribution certificate.

Is that certificate an App Store cert, an Ad Hoc distribution cert, or an Enterprise cert?

**Comment by sankalpanand** [comment]
@jmoody Good point! I generated a new developer certificate, regenerated the provisioning profile for that certificate and it worked.
