### ISSUE TITLE
Ensure that keyboard settings on iOS Simulators are correct before launching tests

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#701]
For inspiration see this commit:

* https://github.com/bootstraponline/run_loop/commit/984bb22474cf9fa4518d42883568bb5ef7d2a27e

The `RunLoop::SimControl` class was removed (deprecated) in 3.0.

We can probably use some of the logic from that class to help find the correct plist(s).

**Comment by jmoody** [comment]
Correct.  In the past we have controlled this by adjust the simulator plist.

**Comment by JoeSSS** [comment]
Ah, I didn’t know we could control it like this. This is a nice thing to fix, I’m getting this question at work quite often)

**Comment by JoeSSS** [comment]
WIP - https://github.com/calabash/run_loop/pull/702/
