### ISSUE TITLE
Device names with apostrophes cause invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by coquifrogs** [calabash/run_loop#74]
OS X 10.10 Xcode 6.1

```
$ xcrun instruments -s devices

Known Devices:
John’s MacBook Pro (3) [515DA020-6292-5EC9-9489-93B2BDCFBDED]
```

Note the apostrophe is UTF-8.

Error stack trace is:

  invalid byte sequence in US-ASCII (ArgumentError)
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.1.0/lib/run_loop/xctools.rb:152:in `split'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.1.0/lib/run_loop/xctools.rb:152:in`block (2 levels) in instruments'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in`popen3'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.1.0/lib/run_loop/xctools.rb:150:in `block in instruments'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.1.0/lib/run_loop/xctools.rb:155:in`call'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.1.0/lib/run_loop/xctools.rb:155:in `instruments'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.1.0/lib/run_loop/sim_control.rb:863:in`sim_details'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.1.0/lib/run_loop/sim_control.rb:290:in `enable_accessibility_on_sims'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.1.0/lib/run_loop/core.rb:95:in`run_with_options'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.1.0/lib/run_loop/core.rb:690:in `run'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.11.4/lib/calabash-cucumber/launcher.rb:732:in`block in new_run_loop'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.11.4/lib/calabash-cucumber/launcher.rb:730:in `times'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.11.4/lib/calabash-cucumber/launcher.rb:730:in`new_run_loop'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.11.4/lib/calabash-cucumber/launcher.rb:605:in `relaunch'

**Comment by jmoody** [comment]
@coquifrogs 

At long last, I have reproduced and I now understand the error of my ways.

Working on a fix.

@michaelkirk @svevang @TobiasRoikjer 

The problem is that `read`, which we use everywhere, always returns a string with ASCII-8BIT encoding. 

http://ruby-doc.org/core-2.2.2/IO.html#method-i-read
