### ISSUE TITLE
macos Monterey support?

### ISSUE THREAD

**Issue by DragonClub** [calabash/run_loop#775]
When will macos monterey be supported?

**Comment by JoeSSS** [comment]
is there something not working?

**Comment by DragonClub** [comment]
> is there something not working?

2021-11-09 09:32:49.630 iOSDeviceManager[37484:1622642] *** Assertion failure in -[FBDeviceControlFrameworkLoader_Xcode loadPrivateFrameworksOrAbort], FBControlCoreFrameworkLoader.m:84

2021-11-09 09:32:49.633 iOSDeviceManager[37484:1622642] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to load private frameworks for FBSimulatorControl with error Error Domain=com.facebook.FBControlCore Code=0 "Error loading bundle at /Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework and it was not a linking issue" UserInfo={NSLocalizedDescription=Error loading bundle at /Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework and it was not a linking issue, NSUnderlyingError=0x6000028f06f0 {Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework/IBAutolayoutFoundation, 0x0109): Library not loaded: @rpath/AssetCatalogFoundation.framework/Versions/A/AssetCatalogFoundation

  Referenced from: /Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework/Versions/A/IBAutolayoutFoundation

  Reason: tried: '/Users/DeviceAgent/MacOS/../Frameworks/AssetCatalogFoundation.framework/Versions/A/AssetCatalogFoundation' (no such file), '/Library/Frameworks/AssetCatalogFoundation.framework/Versions/A/AssetCatalogFoundation' (no such file), '/System/Library/Frameworks/AssetCatalogFoundation.framework/Versions/A/AssetCatalogFoundation' (no such file)" UserInfo={NSLocalizedDescription=The bundle “IBAutolayoutFoundation” couldn’t be loaded., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework/IBAutolayoutFoundation, NSDebugDescription=dlopen(/Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework/IBAutolayoutFoundation, 0x0109): Library not loaded: @rpath/AssetCatalogFoundation.framework/Versions/A/AssetCatalogFoundation

  Referenced from: /Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework/Versions/A/IBAutolayoutFoundation

  Reason: tried: '/Users/DeviceAgent/MacOS/../Frameworks/AssetCatalogFoundation.framework/Versions/A/AssetCatalogFoundation' (no such file), '/Library/Frameworks/AssetCatalogFoundation.framework/Versions/A/AssetCatalogFoundation' (no such file), '/System/Library/Frameworks/AssetCatalogFoundation.framework/Versions/A/AssetCatalogFoundation' (no such file), NSBundlePath=/Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework, NSLocalizedFailureReason=The bundle couldn’t be loaded.}}}'

*** First throw call stack:

(

	0   CoreFoundation                      0x00007ff81be0262b __exceptionPreprocess + 242

	1   libobjc.A.dylib                     0x00007ff81bb64dce objc_exception_throw + 48

	2   Foundation                          0x00007ff81cbe0653 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 267

	3   FBControlCore                       0x000000010d41ed79 -[FBControlCoreFrameworkLoader loadPrivateFrameworksOrAbort] + 521

	4   FBDeviceControl                     0x000000010d2fc11e __33-[FBDeviceSet primeDeviceManager]_block_invoke + 94

	5   libdispatch.dylib                   0x00007ff81bb07cc9 _dispatch_client_callout + 8

	6   libdispatch.dylib                   0x00007ff81bb08ec1 _dispatch_once_callout + 20

	7   FBDeviceControl                     0x000000010d2fc07f -[FBDeviceSet primeDeviceManager] + 159

	8   FBDeviceControl                     0x000000010d2fcbe3 -[FBDeviceSet dvtDeviceWithUDID:] + 67

	9   FBDeviceControl                     0x000000010d2ff556 -[FBDevice dvtDevice] + 118

	10  FBDeviceControl                     0x000000010d304ba6 __63-[FBiOSDeviceOperator waitForDeviceToBecomeAvailableWithError:]_block_invoke + 70

	11  FBControlCore                       0x000000010d3f0a21 -[FBRunLoopSpinner spinUntilTrue:error:] + 193

	12  FBDeviceControl                     0x000000010d30437b -[FBiOSDeviceOperator waitForDeviceToBecomeAvailableWithError:] + 299

	13  iOSDeviceManager                  0x0000000104b99f25 +[PhysicalDevice withID:] + 235

	14  iOSDeviceManager                  0x0000000104ba29af +[Device withID:] + 118

	15  iOSDeviceManager                  0x0000000104ba5c36 +[Command deviceFromArgs:] + 127

	16  iOSDeviceManager                  0x0000000104b9d37b +[InstallAppCommand execute:] + 315

	17  iOSDeviceManager                  0x0000000104ba8798 +[CLI process:] + 1118

	18  iOSDeviceManager                  0x0000000104b94489 main + 121

	19  dyld                                0x0000000204d874fe start + 462

	20  ???                                 0x0000000000000003 0x0 + 3

)

libc++abi: terminating with uncaught exception of type NSException

**Comment by JoeSSS** [comment]
do you use the latest versions of everything? works fine for me, but on the
simulator

**Comment by JoeSSS** [comment]
it looks like I did not build a new DeviceManager binary in the last run_loop release, will try to release a new version soon

**Comment by JoeSSS** [comment]
please test run_loop 4.6.1

**Comment by DragonClub** [comment]
> please test run_loop 4.6.1

macOS : 12.0.1 Monterey
Xcode : 13.1

It has been resolved to 4.6.1 version. Thank you. :)
