### ISSUE TITLE
Using "tap_keyboard_action_key" is typing "\n" instead of search key on the keyboard with calabash 0.11.5.pre3 on iOS 7

### ISSUE THREAD

**Issue by sam0901** [calabash/run_loop#95]
After entering text in a textField, keeping focus still in the text Field,
using "tap_keyboard_action_key" is typing \n instead of taping the search key on the keyboard.

OS: iOS 7.
Calabash 0.11.5.pre3
run_loop 1.2.0.pre2

**Comment by jmoody** [comment]
Please reopen if you are still having trouble after the 1.2.0 release.

**Comment by sam0901** [comment]
Sure i will....

Samba Tiyyagura
